### ISSUE TITLE
error lnk2001

### ISSUE THREAD

**Issue by CrazyJiajialin** [CesiumGS/cesium-unreal-samples#52]
![image](https://github.com/CesiumGS/cesium-unreal-samples/assets/96040952/5f529cba-8e2e-4e75-9829-13678bf3cca5)

**Comment by CrazyJiajialin** [comment]
I compiled cesium-native times wrong, this is what happened?

**Comment by kring** [comment]
Most likely you need to upgrade your version of Visual Studio. If that doesn't work, please post a followup to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead. And copy/paste the actual text of the errors instead of grabbing a screenshot, because we can't easily translate a screenshot.
